### ISSUE TITLE
Use brew cask for VirtualBox

### ISSUE THREAD

**Issue by markogresak** [jonathanong/osx-webdev-setup#4]
> VirtualBox - for VMs, which can't be install using Homebrew

Can be done with [`brew cask`](http://caskroom.io/).

Install brew cask:

``` sh
brew install caskroom/cask/brew-cask
```

Install VirtualBox:

``` sh
brew cask install virtualbox
```

It also supports installation of other suggested programs, such as iStat menus, Atom, Sublime text and probably every other GUI app you can think of.

**Comment by jonathanong** [comment]
does it handle autoupdates for atom and such? i remember using this a while ago and it made things more confusing than just downloading atom from their site and letting it autoupdate itself

**Comment by markogresak** [comment]
Automatic updates are a thing of applications, not the underlying install process. I have most of my apps installed via brew cask and they all autoupdate as they would otherwise.

**Comment by kasperlewau** [comment]
I'll second the praise for brew cask.

Like Marko, I don't think its in the scope of brew cask to handle autoupdates. And seeing as how cask is just another tap, `update`/`upgrade` _works™ like normal brew._

---

With that said, I think the biggest selling point of `cask` _(atleast for me)_ is when its used in conjunction with a Brewfile a la [homebrew-bundle](https://github.com/Homebrew/homebrew-bundle).
Honestly, I can't see myself setting up a new OSX environment without either of the two, after doing things like this:

`$ brew tap homebrew/bundle`

``` bash
## Brewfile
# tap tap tap
tap phinze/cask
tap caskroom/versions

# get cask
install brew-cask

# issue regular 'brew install' commands
install nvm
install git
install tmux

# issue 'brew cask install' commands
cask install alfred # f-cking, cannot live without. 
cask install google-chrome
cask install utorrent
cask install vlc

# sync cask with alfred
cask alfred
```

`$ cd /path/where/Brewfile; brew bundle;`

> shower, fetch beer, come back -  OSX machine fully set up and running o/

**Comment by jonathanong** [comment]
no longer use virtualbox or a lot of these things so I'm gonna close this.
